Repository DevCVTeam/DevCV-backend, pull requests merged in 2024-07, with the labels that each got.

#99 🔧 [Build] junit, assertj 의존성 추가
  build.gradle
Labels: 테스트

#101 🎨 [Refactor] @CrossOrigin origins,allowedHeaders 수정(#100)
  src/main/java/com/devcv/member/presentation/MemberController.java
Labels: 버그

#103 🐛 [Fix] 주문 예외 로직 수정 #102
  src/main/java/com/devcv/order/application/OrderService.java
Labels: 수정

#105 🎨 [Refactor] MemberEntity Notnull 수정, 소셜로그인 Response 수정(#104)
  src/main/java/com/devcv/member/domain/Member.java
  src/main/java/com/devcv/member/presentation/MemberController.java
Labels: 리팩토링

#107 🎨 [Refactor] 구글로그인수정(#106)
  src/main/java/com/devcv/member/domain/dto/profile/GoogleProfile.java
Labels: 버그, 리팩토링

#113 🐛 [Fix] 구매후기 등록 에러사항 수정
  src/main/java/com/devcv/order/repository/OrderRepository.java
  src/main/java/com/devcv/order/repository/OrderResumeRepository.java
  src/main/java/com/devcv/review/application/ReviewService.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
Labels: 버그, 우선순위높음

#114 🎨 [Refactor] 주문 관련 response 수정 (#110)
  src/main/java/com/devcv/member/domain/dto/MemberResponse.java
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/dto/OrderDetailResponse.java
  src/main/java/com/devcv/order/domain/dto/OrderResumeDto.java
  src/main/java/com/devcv/order/domain/dto/OrderSheet.java
  src/main/java/com/devcv/order/domain/dto/OrderSheetResume.java
  src/main/java/com/devcv/order/presentation/OrderController.java
  src/main/java/com/devcv/order/repository/OrderResumeRepository.java
Labels: 리팩토링

#115 [Refactor] 회원코드 도메인 아키텍처에 따라 수정(#108)
  src/main/java/com/devcv/admin/presentation/AdminController.java
  src/main/java/com/devcv/auth/application/AuthService.java
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/devcv/auth/filter/JwtFilter.java
  src/main/java/com/devcv/auth/presentation/AuthController.java
  src/main/java/com/devcv/member/application/MemberService.java
  src/main/java/com/devcv/member/domain/Member.java
  src/main/java/com/devcv/member/presentation/MemberController.java
  src/main/java/com/devcv/member/repository/MemberRepository.java
Labels: 수정, 리팩토링

#117 🎨 [Refactor] RefreshToken 로직 수정(#116)
  src/main/java/com/devcv/auth/presentation/AuthController.java
Labels: 버그, 리팩토링

#118 🎨 [Refactor] 이벤트 삭제 api 추가, 지급포인트필드 추가 #111
  src/main/java/com/devcv/admin/application/AdminService.java
  src/main/java/com/devcv/admin/dto/DeletedEventResponse.java
  src/main/java/com/devcv/admin/presentation/AdminController.java
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/event/application/AttendanceEventService.java
  src/main/java/com/devcv/event/application/EventService.java
  src/main/java/com/devcv/event/domain/Event.java
  src/main/java/com/devcv/event/domain/dto/EventRequest.java
  src/main/java/com/devcv/event/domain/dto/EventResponse.java
  src/main/java/com/devcv/event/presentation/EventController.java
  src/main/java/com/devcv/event/repository/EventRepository.java
Labels: 리팩토링

#120 ✨ [Feat] 회원가입시 포인트 지급, 이력서 판매시 포인트 적립 #112
  src/main/java/com/devcv/auth/application/AuthService.java
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/Order.java
  src/main/java/com/devcv/point/domain/Point.java
Labels: 기능개발

#122 🎨 [Refactor] 이력서 조회/등록/수정 서비스 클래스 리팩토링 (#121)
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/infrastructure/CategoryUtil.java
  src/main/java/com/devcv/resume/infrastructure/ResumeValidator.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
Labels: 리팩토링

#124 🎨 [Refactor] 포인트 서비스 메서드에 트랜잭션 추가
  src/main/java/com/devcv/point/application/PointService.java
Labels: 리팩토링

#126 🎨 [Refactor] 이력서 구매후기 리팩토링
  src/main/java/com/devcv/review/application/CommentService.java
  src/main/java/com/devcv/review/application/CommentServiceImpl.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
  src/main/java/com/devcv/review/infrastructure/ReviewValidator.java
  src/main/java/com/devcv/review/presentation/CommentController.java
  src/main/java/com/devcv/review/presentation/ReviewController.java
  src/main/java/com/devcv/review/repository/ReviewRepository.java
Labels: 리팩토링

#128 ✨ [Feat] 구글 사이트맵 등록 위한 조회 api 추가 (#127)
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/dto/ResumeSitemapDto.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
Labels: 기능개발

#129 Merge develop branch to main
  src/main/java/com/devcv/auth/application/AuthService.java
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/Order.java
  src/main/java/com/devcv/point/application/PointService.java
  src/main/java/com/devcv/point/domain/Point.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/dto/ResumeSitemapDto.java
  src/main/java/com/devcv/resume/infrastructure/CategoryUtil.java
  src/main/java/com/devcv/resume/infrastructure/ResumeValidator.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
  src/main/java/com/devcv/review/application/CommentService.java
  src/main/java/com/devcv/review/application/CommentServiceImpl.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
  src/main/java/com/devcv/review/infrastructure/ReviewValidator.java
  src/main/java/com/devcv/review/presentation/CommentController.java
  src/main/java/com/devcv/review/presentation/ReviewController.java
  src/main/java/com/devcv/review/repository/ReviewRepository.java
Labels: 기능개발

#131 🐛 [Fix] 결제페이지에 누락된 이력서 썸네일 주소 추가. (#130)
  src/main/java/com/devcv/order/domain/dto/OrderSheetResume.java
Labels: 수정

#132 결제페이지 썸네일 이미지 추가
  src/main/java/com/devcv/order/domain/dto/OrderSheetResume.java
Labels: 기능개발
