Repository DevCVTeam/DevCV-backend, pull requests merged in 2024-06, with the labels that each got.

#13 📝 [docs] issue, pr 템플릿 추가 (#9)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: 공용

#15 ♻️ [FEAT] 로그인,회원가입,아이디/비밀번호 찾기, 이메일인증, 회원정보수정(비밀번호 수정) 구현 (#12)
  build.gradle
  src/main/java/com/devcv/DevcvApplication.java
  src/main/java/com/devcv/common/exception/AuthLoginException.java
  src/main/java/com/devcv/common/exception/DuplicationException.java
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/common/exception/NotNullException.java
  src/main/java/com/devcv/common/exception/NotSignUpException.java
  src/main/java/com/devcv/common/exception/UnAuthorizedException.java
  src/main/java/com/devcv/member/Application/memberService.java
  src/main/java/com/devcv/member/Domain/DefaultNicknamePolicy.java
  src/main/java/com/devcv/member/Domain/member.java
  src/main/java/com/devcv/member/Infrastructure/DefaultNicknamePolicyImpl.java
  src/main/java/com/devcv/member/Presentation/memberController.java
  src/main/java/com/devcv/member/Repository/memberRepository.java
  src/main/java/com/devcv/member/application/MailService.java
  src/main/java/com/devcv/member/application/MemberService.java
  src/main/java/com/devcv/member/domain/Member.java
  src/main/java/com/devcv/member/domain/dto/CompanyType.java
  src/main/java/com/devcv/member/domain/dto/GoogleOAuthToken.java
  src/main/java/com/devcv/member/domain/dto/GoogleProfile.java
  src/main/java/com/devcv/member/domain/dto/JobType.java
  src/main/java/com/devcv/member/domain/dto/KakaoOAuthToken.java
  src/main/java/com/devcv/member/domain/dto/KakaoProfile.java
  src/main/java/com/devcv/member/domain/dto/RoleType.java
  src/main/java/com/devcv/member/domain/dto/SocialType.java
  src/main/java/com/devcv/member/infrastructure/ListStringConverter.java
  src/main/java/com/devcv/member/presentation/MemberController.java
  src/main/java/com/devcv/member/repository/MemberRepository.java
  src/test/java/com/devcv/member/presentation/MemberControllerTest.java
Labels: 기능개발

#16 ✨ [feat] 주문 기능 MVP 구현 (#10)
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/Order.java
  src/main/java/com/devcv/order/domain/OrderNumberGenerator.java
  src/main/java/com/devcv/order/domain/OrderStatus.java
  src/main/java/com/devcv/order/domain/PayType.java
  src/main/java/com/devcv/order/domain/dto/OrderRequest.java
  src/main/java/com/devcv/order/domain/dto/OrderResponse.java
  src/main/java/com/devcv/order/domain/dto/OrderSheet.java
  src/main/java/com/devcv/order/presentation/OrderController.java
  src/main/java/com/devcv/order/repository/OrderRepository.java
Labels: 기능개발

#18 🐛 [FIX] 이력서 등록 기능 오류 수정(#17)
  src/main/java/com/devcv/register/application/ResumeServiceImpl.java
  src/main/java/com/devcv/register/repository/CategoryRepository.java
Labels: 버그

#23 🐛 [FIX] 사용되지않는 테스트코드삭제(#22)
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/test.html
  src/test/java/com/devcv/member/presentation/MemberControllerTest.java
Labels: 버그

#27 ✨ [feat] 포인트 기능 구현 #20
  src/main/java/com/devcv/member/domain/Member.java
  src/main/java/com/devcv/point/application/PointService.java
  src/main/java/com/devcv/point/domain/Point.java
  src/main/java/com/devcv/point/domain/TransactionType.java
  src/main/java/com/devcv/point/dto/PointRequestDto.java
  src/main/java/com/devcv/point/presentation/PointController.java
  src/main/java/com/devcv/point/repository/PointRepository.java
Labels: 기능개발

#30 🐛 [Fix] resume 객체 생성안되는 문제 해결 (#28)
  src/main/java/com/devcv/member/domain/Member.java
Labels: 수정

#31 🎨 [Refactor] 패키지, dto 명 수정 (#25)
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/Order.java
  src/main/java/com/devcv/order/domain/dto/OrderSheet.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/Category.java
  src/main/java/com/devcv/resume/domain/Resume.java
  src/main/java/com/devcv/resume/domain/ResumeImage.java
  src/main/java/com/devcv/resume/domain/dto/CategoryDto.java
  src/main/java/com/devcv/resume/domain/dto/ResumeDto.java
  src/main/java/com/devcv/resume/domain/dto/ResumeRequest.java
  src/main/java/com/devcv/resume/domain/dto/ResumeResponse.java
  src/main/java/com/devcv/resume/domain/enumtype/CompanyType.java
  src/main/java/com/devcv/resume/domain/enumtype/ResumeStatus.java
  src/main/java/com/devcv/resume/domain/enumtype/StackType.java
  src/main/java/com/devcv/resume/exception/MemberNotFoundException.java
  src/main/java/com/devcv/resume/exception/ResumeNotFoundException.java
  src/main/java/com/devcv/resume/exception/S3Exception.java
  src/main/java/com/devcv/resume/infrastructure/ListStringConverter.java
  src/main/java/com/devcv/resume/infrastructure/S3Uploader.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
  src/main/java/com/devcv/resume/repository/CategoryRepository.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
Labels: 리팩토링

#32 ✨ [Feat] 이력서 목록, 카테고리별, 상세 조회 기능 구현 (#25)
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/dto/PaginatedResumeResponse.java
  src/main/java/com/devcv/resume/domain/dto/ResumeDto.java
  src/main/java/com/devcv/resume/domain/dto/ResumeResponse.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
Labels: 기능개발

#39 🎨 [Refactor] Member 엔티티 변수명 수정
  src/main/java/com/devcv/member/domain/Member.java
  src/main/java/com/devcv/member/domain/dto/MemberModifyRequest.java
  src/main/java/com/devcv/resume/application/.ResumeServiceImpl.java.swp
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/dto/ResumeDto.java
Labels: 수정

#35 ✨ [Feat] 승인상태, 이력서 수정 및 삭제 고려한 Controller 수정 (#34)
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
Labels: 수정, 우선순위높음

#38 ✨ [Feat] 출석체크 이벤트 기능 MVP 구현 (#37)
  src/main/java/com/devcv/event/application/AttendanceEventService.java
  src/main/java/com/devcv/event/application/EventService.java
  src/main/java/com/devcv/event/domain/AttendanceEvent.java
  src/main/java/com/devcv/event/domain/Event.java
  src/main/java/com/devcv/event/domain/dto/AttendanceListResponse.java
  src/main/java/com/devcv/event/domain/dto/AttendanceRequest.java
  src/main/java/com/devcv/event/domain/dto/EventRequest.java
  src/main/java/com/devcv/event/presentation/AttendanceController.java
  src/main/java/com/devcv/event/presentation/EventController.java
  src/main/java/com/devcv/event/repository/AttendanceEventRepository.java
  src/main/java/com/devcv/event/repository/EventRepository.java
Labels: 기능개발

#41 ✨ [Feat] 이력서 등록 기능 security 추가 (#40)
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/event/application/AttendanceEventService.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/Category.java
  src/main/java/com/devcv/resume/domain/dto/ResumeRequest.java
  src/main/java/com/devcv/resume/domain/dto/ResumeResponse.java
  src/main/java/com/devcv/resume/exception/HttpMessageNotReadableException.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
Labels: 기능개발

#45 ♻️ [Chore] 회원로그인 응답값, RESTful API 요청에 맞게 수정
  src/main/java/com/devcv/auth/application/AuthService.java
  src/main/java/com/devcv/auth/application/MemberDetailsService.java
  src/main/java/com/devcv/auth/config/CorsConfig.java
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/auth/details/MemberDetails.java
  src/main/java/com/devcv/auth/exception/JwtExpiredException.java
  src/main/java/com/devcv/auth/exception/JwtIllegalArgumentException.java
  src/main/java/com/devcv/auth/exception/JwtInvalidSignException.java
  src/main/java/com/devcv/auth/exception/JwtUnsupportedException.java
  src/main/java/com/devcv/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/devcv/auth/filter/JwtFilter.java
  src/main/java/com/devcv/auth/filter/SecurityUtil.java
  src/main/java/com/devcv/auth/jwt/JwtProvider.java
  src/main/java/com/devcv/auth/jwt/JwtTokenDto.java
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/event/application/AttendanceEventService.java
  src/main/java/com/devcv/member/application/MemberService.java
  src/main/java/com/devcv/member/domain/Member.java
  src/main/java/com/devcv/member/domain/MemberLog.java
  src/main/java/com/devcv/member/domain/dto/MemberLoginRequest.java
  src/main/java/com/devcv/member/domain/dto/MemberLoginResponse.java
  src/main/java/com/devcv/member/domain/dto/MemberSignUpRequest.java
  src/main/java/com/devcv/member/domain/enumtype/CompanyType.java
  src/main/java/com/devcv/member/domain/enumtype/JobType.java
  src/main/java/com/devcv/member/domain/enumtype/RoleType.java
  src/main/java/com/devcv/member/domain/enumtype/SocialType.java
  src/main/java/com/devcv/member/exception/SocialDataException.java
  src/main/java/com/devcv/member/exception/SocialLoginException.java
  src/main/java/com/devcv/member/exception/SocialMemberUpdateException.java
  src/main/java/com/devcv/member/presentation/MemberController.java
  src/main/java/com/devcv/member/repository/MemberLogRepository.java
  src/main/java/com/devcv/member/repository/MemberRepository.java
  src/main/java/com/devcv/point/application/PointService.java
  src/main/java/com/devcv/point/domain/Point.java
  src/main/java/com/devcv/point/presentation/PointController.java
  src/main/java/com/devcv/point/repository/PointRepository.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
Labels: 기능개발, 리팩토링

#47 🐛 [Fix]젠킨스에러 관련 수정(#46)
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/auth/exception/JwtExpiredException.java
  src/main/java/com/devcv/auth/exception/JwtIllegalArgumentException.java
  src/main/java/com/devcv/auth/exception/JwtInvalidSignException.java
  src/main/java/com/devcv/auth/exception/JwtUnsupportedException.java
  src/main/java/com/devcv/event/application/AttendanceEventService.java
  src/main/java/com/devcv/event/application/EventService.java
  src/main/java/com/devcv/event/domain/AttendanceEvent.java
  src/main/java/com/devcv/event/domain/Event.java
  src/main/java/com/devcv/event/domain/dto/AttendanceListResponse.java
  src/main/java/com/devcv/event/domain/dto/AttendanceRequest.java
  src/main/java/com/devcv/event/domain/dto/EventRequest.java
  src/main/java/com/devcv/event/presentation/AttendanceController.java
  src/main/java/com/devcv/event/presentation/EventController.java
  src/main/java/com/devcv/event/repository/AttendanceEventRepository.java
  src/main/java/com/devcv/event/repository/EventRepository.java
  src/main/java/com/devcv/member/domain/MemberLog.java
  src/main/java/com/devcv/member/exception/SocialDataException.java
  src/main/java/com/devcv/member/exception/SocialLoginException.java
  src/main/java/com/devcv/member/exception/SocialMemberUpdateException.java
  src/main/java/com/devcv/member/repository/MemberLogRepository.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/dto/PaginatedResumeResponse.java
  src/main/java/com/devcv/resume/exception/HttpMessageNotReadableException.java
Labels: 버그

#51 ✨ [Feat] 주문 기능 2차 MVP 개발(#42)
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/Order.java
  src/main/java/com/devcv/order/domain/dto/OrderRequest.java
  src/main/java/com/devcv/order/domain/dto/OrderResponse.java
  src/main/java/com/devcv/order/presentation/OrderController.java
  src/main/java/com/devcv/order/repository/OrderRepository.java
  src/main/java/com/devcv/point/application/PointService.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
  src/main/java/com/devcv/review/application/ReviewService.java
Labels: 기능개발

#52 ✨ [Feat]회원로그기능개발(#26)
  build.gradle
  src/main/java/com/devcv/auth/application/AuthService.java
  src/main/java/com/devcv/auth/application/MemberDetailsService.java
  src/main/java/com/devcv/auth/config/CorsConfig.java
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/auth/details/MemberDetails.java
  src/main/java/com/devcv/auth/filter/SecurityUtil.java
  src/main/java/com/devcv/auth/jwt/JwtProvider.java
  src/main/java/com/devcv/member/domain/MemberLog.java
  src/main/java/com/devcv/member/domain/dto/MemberLoginResponse.java
  src/main/java/com/devcv/member/presentation/MemberController.java
  src/main/java/com/devcv/member/repository/MemberLogRepository.java
Labels: 기능개발

#58 ✨ [Feat] 포인트 기능 개선 #43
  src/main/java/com/devcv/point/application/PointService.java
  src/main/java/com/devcv/point/domain/Point.java
  src/main/java/com/devcv/point/dto/PointResponse.java
  src/main/java/com/devcv/point/presentation/PointController.java
Labels: 기능개발

#59 ✨ [Feat] 이력서 구매후기 2차 MVP 기능 구현 (#50)
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/order/repository/OrderRepository.java
  src/main/java/com/devcv/review/application/CommentService.java
  src/main/java/com/devcv/review/application/CommentServiceImpl.java
  src/main/java/com/devcv/review/application/ReviewService.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
  src/main/java/com/devcv/review/domain/Comment.java
  src/main/java/com/devcv/review/domain/Review.java
  src/main/java/com/devcv/review/domain/dto/CommentDto.java
  src/main/java/com/devcv/review/domain/dto/PaginatedReviewResponse.java
  src/main/java/com/devcv/review/domain/dto/ReviewDto.java
  src/main/java/com/devcv/review/exception/AlreadyExistsException.java
  src/main/java/com/devcv/review/exception/ReviewAlreadyExistsException.java
  src/main/java/com/devcv/review/exception/ReviewNotFoundException.java
  src/main/java/com/devcv/review/presentation/CommentController.java
  src/main/java/com/devcv/review/presentation/ReviewController.java
  src/main/java/com/devcv/review/repository/CommentRepository.java
  src/main/java/com/devcv/review/repository/ReviewRepository.java
Labels: 기능개발

#63 ✨ [Feat] 이벤트 기능 2차 MVP 개발 #62
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/common/exception/NotFoundException.java
  src/main/java/com/devcv/event/application/AttendanceEventService.java
  src/main/java/com/devcv/event/application/EventService.java
  src/main/java/com/devcv/event/domain/Event.java
  src/main/java/com/devcv/event/domain/dto/EventListResponse.java
  src/main/java/com/devcv/event/domain/dto/EventResponse.java
  src/main/java/com/devcv/event/presentation/AttendanceController.java
  src/main/java/com/devcv/event/presentation/EventController.java
  src/main/java/com/devcv/event/repository/EventRepository.java
Labels: 기능개발

#61 ✨ [Feat] 이력서상태변경 기능추가,회원예외처리보완(#44)
  src/main/java/com/devcv/admin/presentation/AdminController.java
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/member/application/MemberService.java
  src/main/java/com/devcv/member/presentation/MemberController.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
Labels: 기능개발, 수정

#65 ✨ [Feat] 어드민 기능 구현 #64
  src/main/java/com/devcv/admin/application/AdminService.java
  src/main/java/com/devcv/admin/dto/AdminResumeList.java
  src/main/java/com/devcv/admin/presentation/AdminController.java
  src/main/java/com/devcv/admin/repository/AdminResumeRepository.java
  src/main/java/com/devcv/event/application/EventService.java
  src/main/java/com/devcv/event/presentation/EventController.java
Labels: 기능개발

#72 ✨ [Feat] 이력서 구매후기 조회 기능 수정 (#71)
  src/main/java/com/devcv/review/application/ReviewService.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
  src/main/java/com/devcv/review/domain/dto/PaginatedReviewResponse.java
  src/main/java/com/devcv/review/domain/dto/ReviewDto.java
  src/main/java/com/devcv/review/presentation/ReviewController.java
  src/main/java/com/devcv/review/repository/ReviewRepository.java
Labels: 기능개발, 수정

#74 ✨ [Feat] 주문 예외 처리 로직 추가 #68
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/Order.java
  src/main/java/com/devcv/order/domain/dto/OrderResponse.java
Labels: 기능개발

#76 🎨 [Refactor] 비밀번호 평문 request 수정 및 코드리팩토링(#67)
  src/main/java/com/devcv/admin/presentation/AdminController.java
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/member/application/MemberService.java
  src/main/java/com/devcv/member/domain/dto/MemberLoginRequest.java
  src/main/java/com/devcv/member/domain/dto/MemberModifyAllRequest.java
  src/main/java/com/devcv/member/domain/dto/MemberModifyPasswordRequest.java
  src/main/java/com/devcv/member/domain/dto/MemberMypageResponse.java
  src/main/java/com/devcv/member/domain/enumtype/CompanyType.java
  src/main/java/com/devcv/member/presentation/MemberController.java
  src/main/java/com/devcv/mypage/presentation/MyPageController.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/Resume.java
  src/main/java/com/devcv/resume/domain/dto/ResumeListResponse.java
  src/main/java/com/devcv/resume/domain/enumtype/ResumeStatus.java
  src/main/java/com/devcv/resume/exception/FileNameLengthExceededException.java
  src/main/java/com/devcv/resume/exception/MultipartException.java
  src/main/java/com/devcv/resume/exception/ResumeStatusException.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
Labels: 수정, 리팩토링

#79 🎨 [Refactor] github template 개선 #78
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: 공용, 리팩토링

#82 ✨ [Feat] event 테이블에 eventCategory 추가 #80
  src/main/java/com/devcv/admin/application/AdminService.java
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/event/domain/Event.java
  src/main/java/com/devcv/event/domain/EventCategory.java
  src/main/java/com/devcv/event/domain/dto/EventRequest.java
  src/main/java/com/devcv/event/domain/dto/EventResponse.java
Labels: 기능개발

#86 ✨ [Feat] 관리자 이력서 관리 기능 수정 (#85)
  src/main/java/com/devcv/admin/application/AdminService.java
  src/main/java/com/devcv/admin/dto/AdminResumeList.java
  src/main/java/com/devcv/admin/dto/PaginatedAdminResumeResponse.java
  src/main/java/com/devcv/admin/presentation/AdminController.java
  src/main/java/com/devcv/admin/repository/AdminResumeRepository.java
  src/main/java/com/devcv/resume/application/ResumeService.java
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/domain/enumtype/ResumeStatus.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
Labels: 기능개발, 수정

#87 ✨ [Feat] RefreshToken Cookie에 담아 전송(#84)
  src/main/java/com/devcv/auth/config/JwtSecurityConfig.java
  src/main/java/com/devcv/auth/config/SpringSecurityConfig.java
  src/main/java/com/devcv/auth/dto/RefreshTokenResponse.java
  src/main/java/com/devcv/auth/exception/JwtNotExpiredException.java
  src/main/java/com/devcv/auth/exception/JwtNotFoundRefreshTokenException.java
  src/main/java/com/devcv/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/devcv/auth/filter/JwtFilter.java
  src/main/java/com/devcv/auth/jwt/JwtProvider.java
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/devcv/member/exception/NotMatchMemberIdException.java
  src/main/java/com/devcv/member/presentation/MemberController.java
Labels: 기능개발, 수정

#88 🎨 [Refactor] 주문 기능 리팩토링 #83
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/Order.java
  src/main/java/com/devcv/order/domain/OrderResume.java
  src/main/java/com/devcv/order/domain/OrderStatus.java
  src/main/java/com/devcv/order/domain/dto/CartDto.java
  src/main/java/com/devcv/order/domain/dto/CartOrderRequest.java
  src/main/java/com/devcv/order/domain/dto/OrderListResponse.java
  src/main/java/com/devcv/order/domain/dto/OrderResponse.java
  src/main/java/com/devcv/order/domain/dto/OrderResumeDto.java
  src/main/java/com/devcv/order/presentation/OrderController.java
  src/main/java/com/devcv/order/repository/OrderRepository.java
  src/main/java/com/devcv/order/repository/OrderResumeRepository.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
  src/main/java/com/devcv/review/domain/dto/ReviewDto.java
Labels: 리팩토링

#89 🎨 [Refactor] 이력서 등록 연관 기능 수정
  src/main/java/com/devcv/resume/domain/dto/ResumeResponse.java
  src/main/java/com/devcv/resume/presentation/ResumeController.java
Labels: 수정

#91 [Refactor] 주문 response 수정 #90
  src/main/java/com/devcv/order/application/OrderService.java
  src/main/java/com/devcv/order/domain/OrderResume.java
  src/main/java/com/devcv/order/domain/dto/OrderRequest.java
  src/main/java/com/devcv/order/domain/dto/OrderResponse.java
  src/main/java/com/devcv/order/domain/dto/OrderResumeDto.java
  src/main/java/com/devcv/order/repository/OrderResumeRepository.java
Labels: 리팩토링

#93 ✨ [Feat] vaild 예외 처리 추가, GlobalExceptionHandler 정리 #92
  src/main/java/com/devcv/common/exception/ErrorCode.java
  src/main/java/com/devcv/common/exception/dto/ValidErrorResponse.java
  src/main/java/com/devcv/common/handle/GlobalExceptionHandler.java
Labels: 공용, 리팩토링

#95 🎨 [Refactor] 이력서 판매내역 조회 시 삭제 이력서 제외, dtoToEntity 파라미터 order 엔티티 객체로 수정
  src/main/java/com/devcv/resume/application/ResumeServiceImpl.java
  src/main/java/com/devcv/resume/repository/ResumeRepository.java
  src/main/java/com/devcv/review/application/ReviewService.java
  src/main/java/com/devcv/review/application/ReviewServiceImpl.java
Labels: 수정

#98 🎨 [Refactor] 본인인증으로 정보찾기 List로 수정(#84)
  src/main/java/com/devcv/auth/application/MemberDetailsService.java
  src/main/java/com/devcv/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/devcv/member/application/MemberService.java
  src/main/java/com/devcv/member/domain/dto/MemberFindIdReponse.java
  src/main/java/com/devcv/member/domain/dto/MemberFindIdRequest.java
  src/main/java/com/devcv/member/domain/dto/MemberFindOfPhoneReponse.java
  src/main/java/com/devcv/member/domain/dto/MemberFindOfPhoneRequest.java
  src/main/java/com/devcv/member/domain/dto/MyPageResponse.java
  src/main/java/com/devcv/member/presentation/MemberController.java
  src/main/java/com/devcv/member/repository/MemberRepository.java
Labels: 수정, 리팩토링
